// <auto-generated />
using FreelanceGo_MasterV2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace FreelanceGoMasterV2.Migrations
{
    [DbContext(typeof(dDbContext))]
    [Migration("20180427152107_InitialCreateV2")]
    partial class InitialCreateV2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FreelanceGo_MasterV2.Models.Employer", b =>
                {
                    b.Property<int>("Employer_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<bool>("DelStatus");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Facebook");

                    b.Property<string>("FullName")
                        .IsRequired();

                    b.Property<string>("ID_Card")
                        .IsRequired();

                    b.Property<string>("Line");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("TelephoneNumber");

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.Property<string>("imgName");

                    b.HasKey("Employer_ID");

                    b.ToTable("Employer");
                });
#pragma warning restore 612, 618
        }
    }
}
